// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: TicketService.proto

package ticketservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TicketService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_TicketService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_TicketService_proto_rawDescGZIP(), []int{0}
}

type TicketList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tickets []*TicketOrder `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
}

func (x *TicketList) Reset() {
	*x = TicketList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TicketService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketList) ProtoMessage() {}

func (x *TicketList) ProtoReflect() protoreflect.Message {
	mi := &file_TicketService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketList.ProtoReflect.Descriptor instead.
func (*TicketList) Descriptor() ([]byte, []int) {
	return file_TicketService_proto_rawDescGZIP(), []int{1}
}

func (x *TicketList) GetTickets() []*TicketOrder {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type TicketId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticketid int32 `protobuf:"varint,1,opt,name=ticketid,proto3" json:"ticketid,omitempty"`
}

func (x *TicketId) Reset() {
	*x = TicketId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TicketService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketId) ProtoMessage() {}

func (x *TicketId) ProtoReflect() protoreflect.Message {
	mi := &file_TicketService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketId.ProtoReflect.Descriptor instead.
func (*TicketId) Descriptor() ([]byte, []int) {
	return file_TicketService_proto_rawDescGZIP(), []int{2}
}

func (x *TicketId) GetTicketid() int32 {
	if x != nil {
		return x.Ticketid
	}
	return 0
}

type TicketOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eventid   int32  `protobuf:"varint,1,opt,name=eventid,proto3" json:"eventid,omitempty"`
	Amount    int32  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Location  string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Date      string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Seat      string `protobuf:"bytes,5,opt,name=seat,proto3" json:"seat,omitempty"`
	Fulfilled bool   `protobuf:"varint,6,opt,name=fulfilled,proto3" json:"fulfilled,omitempty"`
	Ticketid  int32  `protobuf:"varint,7,opt,name=ticketid,proto3" json:"ticketid,omitempty"`
}

func (x *TicketOrder) Reset() {
	*x = TicketOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TicketService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketOrder) ProtoMessage() {}

func (x *TicketOrder) ProtoReflect() protoreflect.Message {
	mi := &file_TicketService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketOrder.ProtoReflect.Descriptor instead.
func (*TicketOrder) Descriptor() ([]byte, []int) {
	return file_TicketService_proto_rawDescGZIP(), []int{3}
}

func (x *TicketOrder) GetEventid() int32 {
	if x != nil {
		return x.Eventid
	}
	return 0
}

func (x *TicketOrder) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TicketOrder) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TicketOrder) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TicketOrder) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *TicketOrder) GetFulfilled() bool {
	if x != nil {
		return x.Fulfilled
	}
	return false
}

func (x *TicketOrder) GetTicketid() int32 {
	if x != nil {
		return x.Ticketid
	}
	return 0
}

type TicketCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eventid  int32  `protobuf:"varint,1,opt,name=eventid,proto3" json:"eventid,omitempty"`
	Amount   int32  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Date     string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Seat     string `protobuf:"bytes,5,opt,name=seat,proto3" json:"seat,omitempty"`
}

func (x *TicketCreateRequest) Reset() {
	*x = TicketCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TicketService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCreateRequest) ProtoMessage() {}

func (x *TicketCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TicketService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCreateRequest.ProtoReflect.Descriptor instead.
func (*TicketCreateRequest) Descriptor() ([]byte, []int) {
	return file_TicketService_proto_rawDescGZIP(), []int{4}
}

func (x *TicketCreateRequest) GetEventid() int32 {
	if x != nil {
		return x.Eventid
	}
	return 0
}

func (x *TicketCreateRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TicketCreateRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TicketCreateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TicketCreateRequest) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

type TicketOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticketid int32  `protobuf:"varint,1,opt,name=ticketid,proto3" json:"ticketid,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TicketOrderResponse) Reset() {
	*x = TicketOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TicketService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketOrderResponse) ProtoMessage() {}

func (x *TicketOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TicketService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketOrderResponse.ProtoReflect.Descriptor instead.
func (*TicketOrderResponse) Descriptor() ([]byte, []int) {
	return file_TicketService_proto_rawDescGZIP(), []int{5}
}

func (x *TicketOrderResponse) GetTicketid() int32 {
	if x != nil {
		return x.Ticketid
	}
	return 0
}

func (x *TicketOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_TicketService_proto protoreflect.FileDescriptor

var file_TicketService_proto_rawDesc = []byte{
	0x0a, 0x13, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x42, 0x0a,
	0x0a, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x22, 0x26, 0x0a, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x22, 0xbd, 0x01, 0x0a, 0x0b, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x65, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x13, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x22, 0x4b, 0x0a, 0x13, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x92, 0x03, 0x0a, 0x0d, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x22, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x42, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x12, 0x14, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x17, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x1a, 0x1a, 0x2e, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x1a, 0x22, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x49, 0x64, 0x1a, 0x22, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2e, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TicketService_proto_rawDescOnce sync.Once
	file_TicketService_proto_rawDescData = file_TicketService_proto_rawDesc
)

func file_TicketService_proto_rawDescGZIP() []byte {
	file_TicketService_proto_rawDescOnce.Do(func() {
		file_TicketService_proto_rawDescData = protoimpl.X.CompressGZIP(file_TicketService_proto_rawDescData)
	})
	return file_TicketService_proto_rawDescData
}

var file_TicketService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_TicketService_proto_goTypes = []any{
	(*Empty)(nil),               // 0: ticketservice.Empty
	(*TicketList)(nil),          // 1: ticketservice.TicketList
	(*TicketId)(nil),            // 2: ticketservice.TicketId
	(*TicketOrder)(nil),         // 3: ticketservice.TicketOrder
	(*TicketCreateRequest)(nil), // 4: ticketservice.TicketCreateRequest
	(*TicketOrderResponse)(nil), // 5: ticketservice.TicketOrderResponse
}
var file_TicketService_proto_depIdxs = []int32{
	3, // 0: ticketservice.TicketList.tickets:type_name -> ticketservice.TicketOrder
	4, // 1: ticketservice.TicketService.CreateTicket:input_type -> ticketservice.TicketCreateRequest
	0, // 2: ticketservice.TicketService.GetAllTickets:input_type -> ticketservice.Empty
	2, // 3: ticketservice.TicketService.GetTicket:input_type -> ticketservice.TicketId
	3, // 4: ticketservice.TicketService.UpdateTicket:input_type -> ticketservice.TicketOrder
	2, // 5: ticketservice.TicketService.DeleteTicket:input_type -> ticketservice.TicketId
	5, // 6: ticketservice.TicketService.CreateTicket:output_type -> ticketservice.TicketOrderResponse
	1, // 7: ticketservice.TicketService.GetAllTickets:output_type -> ticketservice.TicketList
	3, // 8: ticketservice.TicketService.GetTicket:output_type -> ticketservice.TicketOrder
	5, // 9: ticketservice.TicketService.UpdateTicket:output_type -> ticketservice.TicketOrderResponse
	5, // 10: ticketservice.TicketService.DeleteTicket:output_type -> ticketservice.TicketOrderResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_TicketService_proto_init() }
func file_TicketService_proto_init() {
	if File_TicketService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TicketService_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TicketService_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TicketList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TicketService_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TicketId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TicketService_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TicketOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TicketService_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TicketCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TicketService_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TicketOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TicketService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TicketService_proto_goTypes,
		DependencyIndexes: file_TicketService_proto_depIdxs,
		MessageInfos:      file_TicketService_proto_msgTypes,
	}.Build()
	File_TicketService_proto = out.File
	file_TicketService_proto_rawDesc = nil
	file_TicketService_proto_goTypes = nil
	file_TicketService_proto_depIdxs = nil
}
